"""Lab tool `read_taxonomy` (generated by lab/build_bundle.py; do not edit)."""

from __future__ import annotations

import json

from omnigent_client.tools import tool

ACTOR = "advocate_b"


@tool
def read_taxonomy(taxonomy_id: str) -> str:
    """
    Read one frozen taxonomy with all labels, confidences and citations.

    :param taxonomy_id: e.g. ``"T_six"``.
    :returns: JSON object.
    """
    from labtools import core

    return json.dumps(core.read_taxonomy(taxonomy_id), ensure_ascii=False)
