"""Lab tool `record_append` (generated by lab/build_bundle.py; do not edit)."""

from __future__ import annotations

import json

from omnigent_client.tools import tool

ACTOR = "advocate_b"


@tool
def record_append(type: str, payload_json: str, links: str = "") -> str:
    """
    Append one entry to the shared, hash-chained research record.

    :param type: One of objective, evidence, critique, candidate_experiments, decision, approval_request, audit, next_experiment, note.
    :param payload_json: JSON object with the content, e.g. ``{"claim": "...", "sources": ["https://..."]}``.
    :param links: Comma-separated ids of related record entries, e.g. ``"r0004,r0007"``.
    :returns: JSON with the new entry id.
    """
    from labtools import core

    return json.dumps(core.record_append(ACTOR, type, payload_json, links, hypothesis_origin="agent"), ensure_ascii=False)
