"""Lab tool `submit_taxonomy` (generated by lab/build_bundle.py; do not edit)."""

from __future__ import annotations

import json

from omnigent_client.tools import tool

ACTOR = "advocate_b"


@tool
def submit_taxonomy(taxonomy_json: str) -> str:
    """
    Validate and FREEZE a taxonomy so it can be tested. A frozen taxonomy can never be changed.

    :param taxonomy_json: JSON with taxonomy_id, lang, title, source_claim, labels (``{unit: {"label": str|null, "confidence": "high|medium|contested", "citation": url|"uncertain", "note": str}}``).
    :returns: JSON with sha256 and record id, or validation problems to fix.
    """
    from labtools import core

    return json.dumps(core.submit_taxonomy(ACTOR, taxonomy_json), ensure_ascii=False)
