"""Lab tool `openalex_search` (generated by lab/build_bundle.py; do not edit)."""

from __future__ import annotations

import json

from omnigent_client.tools import tool

ACTOR = "advocate_b"


@tool
def openalex_search(query: str) -> str:
    """
    Search scholarly literature (OpenAlex). Use the returned URLs as citations.

    :param query: e.g. ``"Sima Tan six schools"``.
    :returns: JSON with titles, years, authors, venues, URLs.
    """
    from labtools import core

    return json.dumps(core.openalex_search(query), ensure_ascii=False)
