"""Lab tool `record_read` (generated by lab/build_bundle.py; do not edit)."""

from __future__ import annotations

import json

from omnigent_client.tools import tool

ACTOR = "skeptic"


@tool
def record_read(last_n: int = 20, type: str = "", actor: str = "") -> str:
    """
    Read recent entries of the shared research record.

    :param last_n: How many entries to return, e.g. ``20``.
    :param type: Optional filter, e.g. ``"result"`` or ``"taxonomy_frozen"``.
    :param actor: Optional filter by agent name, e.g. ``"statistician"``.
    :returns: JSON list of entries.
    """
    from labtools import core

    return json.dumps(core.record_read(last_n, type, actor), ensure_ascii=False)
