"""Lab tool `get_blind_batch` (generated by lab/build_bundle.py; do not edit)."""

from __future__ import annotations

import json

from omnigent_client.tools import tool

ACTOR = "prober_a"


@tool
def get_blind_batch(batch_id: int) -> str:
    """
    Get one batch of masked passages for the recognition probe.

    :param batch_id: e.g. ``0``.
    :returns: JSON with passages.
    """
    from labtools import core

    return json.dumps(core.get_blind_batch(batch_id), ensure_ascii=False)
