"""Lab tool `submit_probe` (generated by lab/build_bundle.py; do not edit)."""

from __future__ import annotations

import json

from omnigent_client.tools import tool

ACTOR = "prober_a"


@tool
def submit_probe(batch_id: int, guesses_json: str) -> str:
    """
    Submit source guesses for one batch.

    :param batch_id: e.g. ``0``.
    :param guesses_json: JSON list of ``{"id": ..., "guess_book": ..., "confidence": 0.0-1.0}``.
    :returns: JSON.
    """
    from labtools import core

    return json.dumps(core.submit_probe(ACTOR, batch_id, guesses_json), ensure_ascii=False)
