"""Lab tool `request_publication` (generated by lab/build_bundle.py; do not edit)."""

from __future__ import annotations

import json

from omnigent_client.tools import tool

ACTOR = "planner"


@tool
def request_publication(conclusion_json: str) -> str:
    """
    Publish the lab's conclusion. Blocked by policy until instrument validation passed; then a human must approve.

    :param conclusion_json: JSON with findings per hypothesis (numbers + record ids), limitations, validation still needed, next experiment.
    :returns: JSON.
    """
    from labtools import core

    return json.dumps(core.request_publication(ACTOR, conclusion_json), ensure_ascii=False)
