"""Lab tool `list_taxonomies` (generated by lab/build_bundle.py; do not edit)."""

from __future__ import annotations

import json

from omnigent_client.tools import tool

ACTOR = "advocate_a"


@tool
def list_taxonomies() -> str:
    """
    List all frozen taxonomies (id, language, title, classes).

    :returns: JSON list.
    """
    from labtools import core

    return json.dumps(core.list_taxonomies(), ensure_ascii=False)
