"""Lab tool `corpus_info` (generated by lab/build_bundle.py; do not edit)."""

from __future__ import annotations

import json

from omnigent_client.tools import tool

ACTOR = "advocate_a"


@tool
def corpus_info(lang: str) -> str:
    """
    List the corpus units that a taxonomy can label (no labels, no results).

    :param lang: ``"zh"`` (early Chinese books) or ``"en"`` (pre-1931 philosophy authors).
    :returns: JSON object.
    """
    from labtools import core

    return json.dumps(core.corpus_info(lang), ensure_ascii=False)
