"""Lab tool `check_citation` (generated by lab/build_bundle.py; do not edit)."""

from __future__ import annotations

import json

from omnigent_client.tools import tool

ACTOR = "historian"


@tool
def check_citation(url: str) -> str:
    """
    Fetch a citation URL and report HTTP status and page title.

    :param url: e.g. ``"https://doi.org/10.2307/3096138"``.
    :returns: JSON.
    """
    from labtools import core

    return json.dumps(core.check_citation(url), ensure_ascii=False)
