"""Lab tool `wikipedia_lookup` (generated by lab/build_bundle.py; do not edit)."""

from __future__ import annotations

import json

from omnigent_client.tools import tool

ACTOR = "historian"


@tool
def wikipedia_lookup(title: str, lang: str = "en") -> str:
    """
    Fetch the plain-text extract of a Wikipedia article and its URL.

    :param title: Article title, e.g. ``"Guanzi (text)"``.
    :param lang: ``"en"`` or ``"zh"``.
    :returns: JSON.
    """
    from labtools import core

    return json.dumps(core.wikipedia_lookup(title, lang), ensure_ascii=False)
